[package]
name = "parse-changelog-internal-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
fs-err = "2"
prettyplease = "0.1.11"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "visit-mut"] }
walkdir = "2"
